# Samna Salta Bot Configuration

bot:
  name: "Samna Salta Bot"
  description: "Traditional Yemenite food ordering bot"
  version: "1.0.0"

products:
  categories:
    - bread
    - spread
    - spice
    - beverage

delivery:
  pickup:
    enabled: true
    charge: 0.0
  delivery:
    enabled: true
    charge: 5.0
    currency: "ILS"

business_hours:
  hilbeh:
    days: ["wednesday", "thursday", "friday"]
    hours: "09:00-18:00"

notifications:
  admin:
    order_notifications: true
    error_notifications: true

admin:
  chat_id: "598829473"  # Replace with your actual admin Telegram user ID

logging:
  level: "INFO"
  format: "json"
  file: "logs/bot.log" 