"""
Conversation states for the Telegram bot.
"""

from telegram.ext import ConversationHandler

# Onboarding states
ONBOARDING_LANGUAGE = 1
ONBOARDING_NAME = 2
ONBOARDING_PHONE = 3
ONBOARDING_DELIVERY_METHOD = 4
ONBOARDING_DELIVERY_ADDRESS = 5

# Cart states
CART_QUANTITY = 6
CART_OPTIONS = 7

# Order states
ORDER_CONFIRMATION = 8
ORDER_DELIVERY_ADDRESS = 9

# Admin states
AWAITING_ORDER_ID = 10
AWAITING_PRODUCT_DETAILS = 11
AWAITING_SEARCH_TERM = 12

# Product creation states
AWAITING_PRODUCT_NAME = 13
AWAITING_PRODUCT_DESCRIPTION = 14
AWAITING_PRODUCT_CATEGORY = 15
AWAITING_PRODUCT_PRICE = 16
AWAITING_PRODUCT_CONFIRMATION = 17

# End conversation
END = ConversationHandler.END 